<a href="https://colab.research.google.com/github/digitechit07/Python-Tutorial-with-Excercise/blob/main/Python_Arrays_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **What Are Arrays in Python?**
In Python, an array is an ordered collection of objects, all of the same type. These characteristics give arrays two main benefits. First, items in an array can be consistently identified by their index, or location, within the array. Second, items in an array are assured to be of the same type.

When creating an array in Python, you must indicate the type of data to be stored. The available types are indicated using codes, which consist of the following:

In [4]:
import array as arr

# Creating an integer array
numbers = arr.array('i', [5, 10, 15])

# Add an element at the end
numbers.append(20)

# Insert an element at index 1
numbers.insert(1, 7)

# Add multiple elements using extend()
numbers.extend([25, 30])

print(numbers)

import array as arr

# Creating an array
numbers = arr.array('i', [10, 20, 30, 40, 50])

# Removing element by value
numbers.remove(30)   # Removes 30

# Removing element by index
numbers.pop(1)       # Removes the element at index 1

print(numbers)

import array as arr

# Creating an array
numbers = arr.array('i', [10, 20, 30, 40, 50])

# Searching for an element
index = numbers.index(30)   # Returns 2

print("Index of 30:", index)

import array as arr

# Creating an array of integers
numbers = arr.array('i', [10, 20, 30, 40, 50, 60])

# Slicing from index 1 to 4 (excluding index 4)
print("Slice from index 1 to 4:", numbers[1:4])

# Slicing from start to index 3
print("Slice from start to index 3:", numbers[:3])

# Slicing from index 2 to end
print("Slice from index 2 to end:", numbers[2:])

import array as arr

# Creating an array of integers
numbers = arr.array('i', [5, 10, 15, 20, 25])

# Updating the element at index 2
numbers[2] = 99

print("Updated array:", numbers)

import array as arr

# Creating an array
numbers = arr.array('i', [10, 20, 30, 10, 40, 10])

# Total elements
print("Total elements:", len(numbers))

# Count of 10
print("Number of times 10 appears:", numbers.count(10))

import array as arr

# Original array
numbers = arr.array('i', [10, 20, 30])

# Array to extend
more_numbers = [40, 50, 60]

# Extending the original array
numbers.extend(more_numbers)

print(numbers)

import array as arr

# Original array
numbers = arr.array('i', [10, 20, 30, 40, 50])

# Reversing the array
numbers.reverse()

print(numbers)
'''
for i, item in enumerate(test_array):
    print(str(i + 1) + ": " + str(item))

example_array = array("i", [2, 4, 6, 8])
another_array = array("i", [20, 40, 60, 80])
combined_array = example_array + another_array
print(combined_array)
'''
import array as arr
a = arr.array('I', [2,4,6,8])
print(a)


from array import*
array_1 = array('i', [1,2,3,4,5])
print (array_1[0])
print (array_1[3])

string1 = input('Enter the elements separated by space ')
print("\n")
arr1 = string1.split()
print('Array = ', arr1)


from array import *
array_1 = array('i', [1,2,3,4,5])
for x in array_1:
  print (x)

from array import *
array_1 = array('i', [1,2,3,4,5])
array_1.insert(1,6)
for x in array_1:
  print (x)


from array import *
array_1 = array('i', [1,2,3,4,5])
array_1.remove(2)
for x in array_1:
  print (x)


from array import *
array_1 = array('i', [1,2,3,4,5])
print (array_1.index(3))


from array import *
array_1 = array('i', [1,2,3,4,5])
array_1[2] = 100
for x in array_1:
  print(x)


Student_marks = [[96, 91, 70, 78, 97], [80, 87, 65, 89, 85], [90, 93, 91, 90, 94], [57, 89, 82, 69, 60], [72, 85, 87, 90, 69]]
print(Student_marks[1])
print(Student_marks[0])
print(Student_marks[2])
print(Student_marks[3][4])


matrix_3d = [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]
print(matrix_3d[0][1][2])
print(matrix_3d[1][0][1])


courses = ["Intellipaat", "Python", "Course"]
x = len(courses)
print(x)


string1 = "5 6 7 8 "  # Corrected string assignment
print("\n")
arr1 = string1.split()  # Splitting the string into a list of strings
print('Array =', arr1)
# Convert string elements to integers
for i in range(len(arr1)):
  arr1[i] = int(arr1[i])
# Calculate and print the sum
print("Sum =", sum(arr1))


numbers = [1, 3, 4, 2]
numbers.sort()
print(numbers)


import numpy as np
a = np.array([2, 4, 6])
b = a[0:2]
print(b)


import numpy as np
list1 = [2,4,6,8,10]
arr1 = np.array(list1)
print (arr1)
print (type(arr1))


def Convert(string):
  a = list(string.split(" "))
  return a
  str1 = "Intellipaat Python Tutorial"
  print(Convert(str1))


import numpy as np
# Creating a simple NumPy array
arr = np.array([1, 2, 3, 4, 5])
print("NumPy Array:", arr)
# Performing element-wise addition
result = arr + 10
print("Result after addition:", result)





array('i', [5, 7, 10, 15, 20, 25, 30])
array('i', [10, 40, 50])
Index of 30: 2
Slice from index 1 to 4: array('i', [20, 30, 40])
Slice from start to index 3: array('i', [10, 20, 30])
Slice from index 2 to end: array('i', [30, 40, 50, 60])
Updated array: array('i', [5, 10, 99, 20, 25])
Total elements: 6
Number of times 10 appears: 3
array('i', [10, 20, 30, 40, 50, 60])
array('i', [50, 40, 30, 20, 10])
array('I', [2, 4, 6, 8])
1
4
Enter the elements separated by space 2 3


Array =  ['2', '3']
1
2
3
4
5
1
6
2
3
4
5
1
3
4
5
2
1
2
100
4
5
[80, 87, 65, 89, 85]
[96, 91, 70, 78, 97]
[90, 93, 91, 90, 94]
60
6
8
3


Array = ['5', '6', '7', '8']
Sum = 26
[1, 2, 3, 4]
[2 4]
[ 2  4  6  8 10]
<class 'numpy.ndarray'>
NumPy Array: [1 2 3 4 5]
Result after addition: [11 12 13 14 15]


# **Type Code	C Type	Python Type	Min. Bytes**
‘b’	signed char	int	1
‘B’	unsigned char	int	1
‘u’	wchar_t	Unicode character	2
‘h’	signed short	int	2
‘H’	unsigned short	int	2
‘i’	signed int	int	2
‘I’	unsigned int	int	2
’l'	signed long	int	4
‘L’	unsigned long	int	4
‘q’	signed long long	int	8
‘Q’	unsigned long long	int	8
‘f’	float	float	4
’d'	double	float	8
Generally, though, for arrays containing numbers, you can focus on using just two of the available codes. Use the i code for arrays containing integers. Use the d code for arrays containing floating point numbers.

In [15]:
import numpy as np
# Creating a simple NumPy array
arr = np.array([1, 2, 3, 4, 5])
print("NumPy Array:", arr)
# Performing element-wise addition
result = arr + 10
print("Result after addition:", result)


import numpy as np
arr_2d = np.array([[1, 2], [3, 4]])  # 2D array
arr_1d = np.array([1, 0])  # 1D array
result = arr_2d + arr_1d  # Broadcasting happens here
print(result)


import time
from array import array
# Array Performance Test with Arithmetic Operations
arr = array('i', range(1000000))  # Create an array of integers
start = time.time()
arr = [x * 2 for x in arr]  # Perform an arithmetic operation on all elements
print("Array Time:", time.time() - start)
# List Performance Test with Arithmetic Operations
lst = (range(1000000))  # Create a list of integers
start = time.time()
lst = [x * 2 for x in lst]  # Perform an arithmetic operation on all elements
print("List Time:", time.time() - start)


list = [3, 6, 9, 12]
print(list)
print(type(list))

array_1 = array("i", [3, 6, 9, 12])
print(array_1)
print(type(array_1))

array_2 = np.array(["numbers", 3, 6, 9, 12])
print (array_2)
print(type(array_2))


array = np.array([3, 6, 9, 12])
division = array/3
print(division)
print (type(division))

import numpy as np
my_array = np.array([5, 2, 8, 1, 9])
sorted_array = np.sort(my_array)
print(sorted_array) # Output: [1 2 5 8 9]

import numpy as np
my_list = [1, 2, 3, 4, 5]
numpy_array = np.array(my_list)
print(numpy_array) # Output: [1 2 3 4 5]

import numpy as np
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
concatenated_array = np.concatenate((array1, array2))
print(concatenated_array) # Output: [1 2 3 4 5 6]

a = ('o',[1.2,3.6,4.7])
print (a)

import array as cam

b = cam.array('i',[1,3,5,7])

print("1st element:",b[0])

print("2nd element:", b[1])

print("Last element:", b[-1])


numbers_list = [22, 5, 42, 5, 52, 48, 62, 5]

numbers_array = ('j',numbers_list)

print(numbers_array[3:6]) # 4th to 6th

print (numbers_array[:-5]) # beginning to 4th

print (numbers_array[4:]) #5th to end

print (numbers_array[:]) #beginning to end



'''
import array as pac

numbers = pac.array( 'm', [5, 10, 7, 1, 2, 3])

#to change the first element

numbers[0] = 6

print(numbers)



#to change the fourth element to fifth element

numbers[3:4] = pac.array( 'm', [8, 9, 4])


# Output:

array('m', [6, 10, 7, 8, 9, 4])
'''
# Python program to demonstrate
# Creation of Array

# importing "array" for array creations
import array as arr

# creating an array with integer type
a = arr.array('i', [1, 2, 3])

# printing original array
print("The new array we just created is: ", end=" ")
for i in range(0, 3):
	print(a[i], end=" ")
print()

# creating an array with double type
b = arr.array('d', [2.5, 3.2, 3.3])

# printing original array
print("\nThe new array we just created is: ", end=" ")
for i in range(0, 3):
	print(b[i], end=" ")

import array

# Creating an empty array of integers
my_array = array.array('i')

# Adding elements to the array
my_array.append(1)
my_array.append(2)
my_array.append(3)

# Print the array
print(my_array)

import array as arr

# Create an array of integers
my_array = arr.array('i')

# Add elements to the array
my_array.append(1)
my_array.append(2)
my_array.append(3)

# Print the array
print(my_array)

from array import *

# Creating an array
my_array = array('i')

# Adding elements to the array
my_array.append(1)
my_array.append(2)
my_array.append(3)

# Print the array
print(my_array)

import array as arr

numbers = arr.array('i',[2,4,6,8,10])

print(numbers)

#output

#array('i', [2, 4, 6, 8, 10])

import array as arr

#array initially provided
numbers = arr.array('i',[10,20,30])

#get the values 20 and 30 only
print(numbers[1:3]) #second to third position

#output
#array('i', [20, 30])


NumPy Array: [1 2 3 4 5]
Result after addition: [11 12 13 14 15]
[[2 2]
 [4 4]]
Array Time: 0.07214713096618652
List Time: 0.11076807975769043
[3, 6, 9, 12]
<class 'list'>
array('i', [3, 6, 9, 12])
<class 'array.array'>
['numbers' '3' '6' '9' '12']
<class 'numpy.ndarray'>
[1. 2. 3. 4.]
<class 'numpy.ndarray'>
[1 2 5 8 9]
[1 2 3 4 5]
[1 2 3 4 5 6]
('o', [1.2, 3.6, 4.7])
1st element: 1
2nd element: 3
Last element: 7
()
()
()
('j', [22, 5, 42, 5, 52, 48, 62, 5])
The new array we just created is:  1 2 3 

The new array we just created is:  2.5 3.2 3.3 array('i', [1, 2, 3])
array('i', [1, 2, 3])
array('i', [1, 2, 3])
array('i', [2, 4, 6, 8, 10])
array('i', [20, 30])


# **Python Arrays vs. Lists**
Often, people talking about arrays in Python are actually referring to Python lists. While lists and arrays share some similarities in Python, they are two distinct types of collections.

The main difference between lists and arrays is that arrays constrain the object type it can store. Lists do not give you a way to limit the types of objects they contain. When using an array, you can be sure that it only contains the type that was specified upon creation.

A single Python list can simultaneously store integers, strings, and dictionaries. You can even add more elements of still other types to an existing list. By contrast, elements in a Python array can only be of one type. An array of integers can only contain integers and can only have other integers added to it.

Aside from this difference, however, you can generally navigate and modify arrays and lists in the same way. All of the operations detailed below for arrays, except for the array() function itself, can be applied to lists as well.

In [17]:
import array as arr

numbers = arr.array('i',[2, 4, 6, 8, 10])

print(len(numbers))

import array as arr

numbers = arr. array('f', [15.5, 30.7, 45.9, 61.2, 75.3])

for number in numbers:
    print(number)

#output
#15.5
#30.7
#45.9
#61.2
#75.3

import array as arr

values = arr.array('f', [15.5, 30.7, 45.9])

#prints each individual value in the array
for value in range(len(values)):
    print(values[value])

#output

#15.5
#30.7
#45.9

import array as arr

numbers = arr.array('i', [10, 20, 30])

# Search for the index of the value 20
print(numbers.index(20))

#Output: 1

import array as arr

numbers = arr.array('i', [10, 20, 30, 10, 20, 30])

# Search for the index of the value 20
# Returns the index number of the first instance of the value 20
print(numbers.index(20))

#Output: 1

# Iterate Python Program to print alternate elements
# of the array

def getAlternates(arr):
    res = []

    # Iterate over all alternate elements
    for i in range(0, len(arr), 2):
        res.append(arr[i])
    return res

if __name__ == "__main__":
    arr = [10, 20, 30, 40, 50]
    res = getAlternates(arr)
    print(" ".join(map(str, res)))

import array

# creating array
int_array = array.array('i', [1, 2, 3, 4])

float_array = array.array('f', [1.1, 2.2, 3.3, 4.4])

# unicode array support is deprecated and will be deleted in Python 4
unicode_array = array.array('u', ['\u0394', '\u2167', '\u007B'])

# printing array
print(int_array)
print(float_array)
print(unicode_array)
print(type(int_array))


import array

int_array = array.array('i', [1, 2, 3, 4])

for a in int_array:
    print(a)

for b in range(0, len(int_array)):
    print(f'int_array[{b}] = {int_array[b]}')


int_array[0] = 1
int_array[1] = 2
int_array[2] = 3
int_array[3] = 4

int_array = array.array('i', [1, 2, 3, 4])
int_array.insert(0, -1)  # -1,1,2,3,4
int_array.insert(2, -2)  # -1,1,-2,2,3,4
print(int_array)


int_array = array.array('i', [1, 2, 3, 4])
int_array.append(-3)
print(int_array)  # array('i', [1, 2, 3, 4, -3])

int_array = array.array('i', [10, 20, 30, 40, 50, 60, 70, 80])
print(int_array[-2])  # 70
print(int_array[-5])  # 40

int_array = array.array('i', [1, 2, 3, 4])
try:
    int_array.remove(20)
except ValueError as ve:
    print(ve)

int_array = array.array('i', [1, 2, 3, 4])
last_element = int_array.pop()
print(last_element)  # 4
print(int_array)  # array('i', [1, 2, 3])

second_element = int_array.pop(1)
print(second_element)  # 2
print(int_array)  # array('i', [1, 3])

int_array = array.array('i', [0, 1, 2, 3, 4, 5])
print(int_array[3:])  # array('i', [3, 4, 5])
print(int_array[:2])  # array('i', [0, 1])
print(int_array[1:3])  # array('i', [1, 2])

# negative index slicing
print(int_array[-2:])  # array('i', [4, 5])
print(int_array[:-2])  # array('i', [0, 1, 2, 3])

int_array = array.array('i', [0, 1, 2, 3, 1, 2])

print(f'1 is found at index {int_array.index(1)}')
try:
    print(int_array.index(20))
except ValueError as ve:
    print(ve)

int_array[0] = -1
int_array[1] = -2
print(int_array)

try:
    int_array[10] = -10
except IndexError as ie:
    print(ie)

int_array = array.array('i', [0, 1, 2, 3])
int_array.reverse()
print(int_array)  # array('i', [3, 2, 1, 0])

int_array = array.array('i', [0, 1, 1, 0])
print(int_array.count(1))  # 2
print(int_array.count(10))  # 0

array1 = array.array('i', [0, 1])
array2 = array.array('i', [2, 3, 4])

array1.extend(array2)
print(array1)  # array('i', [0, 1, 2, 3, 4])

print(array2)  # array('i', [2, 3, 4])
array2.extend([1, 2])
print(array2)  # array('i', [2, 3, 4, 1, 2])

array1 = array.array('i', [1])
array1.extend(set([0,0,0,2]))
print(array1)  # array('i', [1, 0, 2])

int_array = array.array('i', [0, 1, 2, 3])
print(int_array.tolist())  # [0, 1, 2, 3]

# Create an Array
# Import "array" for array creations
import array as arr

# Create an array of integer type
arr1 = arr.array('i', [2, 4, 6, 8])

print("Array is : ", end=" ")
for i in range(0, 4):
	print(arr1[i], end=" ")


# Create an array of float type
arr1 = arr.array('d', [2.0, 4.0, 6.0, 8.0])
print("Array is : ", end=" ")
for i in range(0, 4):
	print(arr1[i], end=" ")



5
15.5
30.700000762939453
45.900001525878906
61.20000076293945
75.30000305175781
15.5
30.700000762939453
45.900001525878906
1
1
10 30 50
array('i', [1, 2, 3, 4])
array('f', [1.100000023841858, 2.200000047683716, 3.299999952316284, 4.400000095367432])
array('u', 'ΔⅧ{')
<class 'array.array'>
1
2
3
4
int_array[0] = 1
int_array[1] = 2
int_array[2] = 3
int_array[3] = 4
array('i', [-1, 1, -2, 2, 3, 4])
array('i', [1, 2, 3, 4, -3])
70
40
array.remove(x): x not in array
4
array('i', [1, 2, 3])
2
array('i', [1, 3])
array('i', [3, 4, 5])
array('i', [0, 1])
array('i', [1, 2])
array('i', [4, 5])
array('i', [0, 1, 2, 3])
1 is found at index 1
array.index(x): x not in array
array('i', [-1, -2, 2, 3, 1, 2])
array assignment index out of range
array('i', [3, 2, 1, 0])
2
0
array('i', [0, 1, 2, 3, 4])
array('i', [2, 3, 4])
array('i', [2, 3, 4, 1, 2])
array('i', [1, 0, 2])
[0, 1, 2, 3]
Array is :  2 4 6 8 Array is :  2.0 4.0 6.0 8.0 

# **Navigating Python Arrays**
There are two ways you can interact with the contents of an array: either through Python’s indexing notation or through looping. Each of these is covered in the sections that follow.

Python Array Indices and Slices
The individual elements of an array can be accessed using indices. Array indices begin at 0. This means that the first element of an array is assigned an index of 0, and each subsequent element’s index progresses from there.

So, to access the first, second, and third elements of the example_array, you use the following index notation: