<a href="https://colab.research.google.com/github/digitechit07/Python-Tutorial-with-Excercise/blob/main/Python_Arrays_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Why use Arrays in Python?**

A combination of Arrays, together with Python could save you a lot of time. As mentioned earlier, arrays help you reduce the overall size of your code, while Python helps you get rid of problematic syntax, unlike other languages.
For example: If you had to store integers from 1-100, you won’t be able to remember 100 variable names explicitly, therefore, you can save them easily using an array.

In [2]:
import array as arr

numbers = arr.array('i', [10, 11, 12, 12, 13])

numbers.remove(12)
print(numbers)   # Output: array('i', [10, 11, 12, 13])

print(numbers.pop(2))   # Output: 12
print(numbers)   # Output: array('i', [10, 11, 13])


a=arr.array('d', [1.1 , 2.1 ,3.1] )
a.append(3.4)
print(a)


a=arr.array('d', [1.1 , 2.1 ,3.1] )
a.extend([4.5,6.3,6.8])
print(a)

a=arr.array('d', [1.1 , 2.1 ,3.1] )
a.insert(2,3.8)
print(a)

a=arr.array('d',[1.1 , 2.1 ,3.1,2.6,7.8])
b=arr.array('d',[3.7,8.6])
c=arr.array('d')
c=a+b
print("Array c = ",c)

a=arr.array('d', [1.1, 2.2, 3.8, 3.1, 3.7, 1.2, 4.6])
print(a.pop())
print(a.pop(3))

a=arr.array('d',[1.1 , 2.1 ,3.1])
a.remove(1.1)
print(a)

a=arr.array('d',[1.1 , 2.1 ,3.1,2.6,7.8])
print(a[0:3])

a=arr.array('d', [1.1, 2.2, 3.8, 3.1, 3.7, 1.2, 4.6])
print("All values")
for x in a:
  print(x)
print("specific values")
for x in a[1:3]:
  print(x)


data = [10, 20, 30, 40, 50]
subset = data[1:4]
print(subset)  # Output: [20, 30, 40]

nums = [4, 1, 3, 2]
nums.sort()
print(nums)  # [1, 2, 3, 4]

import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr)  # Output: [1 2 3 4]

import array
nums = array.array('i', [1, 2, 3])
print(len(nums))  # 3

numbers = [10, 20, 30]
numbers[1] = 25
print(numbers)  # [10, 25, 30]

items = [1, 2, 3]
items.append(4)
print(items)  # [1, 2, 3, 4]

items.pop()
print(items)  # [1, 2, 3]

import array
nums = array.array('i', [1, 2, 3])
nums.append(4)
nums.pop()

for item in ["a", "b", "c"]:
    print(item)

for item in ["a", "b", "c"]:
    print(item)

for i in range(len(items)):
    print(items[i])


scores = [55, 80, 72, 90]
passed = [score for score in scores if score >= 60]
print(passed)  # [80, 72, 90]



matrix = [[1, 2], [3, 4]]
print(matrix[0][1])  # Output: 2



#arrayName = array.array (dataType, [array,items])
import array
arr = array.array('i', [10, 20, 30, 40, 50])


print(arr[2])  # Output: 30

arr[2] = 35
print(arr)  # Output: array('i', [10, 20, 35, 40, 50])

arr.append(60)

arr.insert(1, 15)  # Insert 15 at index 1

arr.remove(40)  # Removes the first occurrence of 40

arr.pop()      # Removes last element
arr.pop(2)     # Removes element at index 2

arr2 = array.array('i', [70, 80])
arr.extend(arr2)

print(arr.index(50))  # Returns index of 50

print(arr.buffer_info())  # Returns memory address and length

print(arr.count(20))  # Count how many times 20 appears

import numpy as np
np_arr = np.array([1, 2, 3, 4, 5])

print(np_arr + 10)         # [11 12 13 14 15]
print(np_arr * 2)          # [2 4 6 8 10]
print(np_arr ** 2)         # [1 4 9 16 25]

print(np_arr.sum())        # 15
print(np_arr.mean())       # 3.0
print(np_arr.min())        # 1
print(np_arr.max())        # 5
print(np_arr.std())        # Standard deviation

arr2D = np.array([[1, 2], [3, 4]])
print(arr2D.shape)         # (2, 2)
print(arr2D.reshape(4, 1))

a = np.array([1, 2])
b = np.array([3, 4])
print(np.hstack((a, b)))   # Horizontal stack: [1 2 3 4]
print(np.vstack((a, b)))   # Vertical stack

print(np_arr > 3)          # [False False False  True  True]
print(np_arr[np_arr > 3])  # [4 5]

unsorted = np.array([3, 1, 5, 2])
print(np.sort(unsorted))   # [1 2 3 5]

print(np.unique(np.array([1, 2, 2, 3, 3, 3])))


'''
import array as arr

arrayName = arr.array(code for data type, [array and its items])
'''


import array as arr

myArr = arr.array('d', [20, 35, 55, 65])

print(myArr)


import array as arr

myArr = arr.array('i', [20, 35, 55, 65])

indOfElement = 2

accessedElement = myArr[indOfElement]

print('Element at 2nd index of array is: ', accessedElement)


import array as arr

myArr = arr.array('i', [20, 35, 55, 65])

myArr.remove(55)

print('This shows that element 55 is removed from the array. Updated Array is: ', myArr)

myArr2 = arr.array('i', [20, 35, 55, 65])

myArr2.pop()

print('This shows that element which is at the last index of array removed. Updated Array is: ', myArr2)




array('i', [10, 11, 12, 13])
12
array('i', [10, 11, 13])
array('d', [1.1, 2.1, 3.1, 3.4])
array('d', [1.1, 2.1, 3.1, 4.5, 6.3, 6.8])
array('d', [1.1, 2.1, 3.8, 3.1])
Array c =  array('d', [1.1, 2.1, 3.1, 2.6, 7.8, 3.7, 8.6])
4.6
3.1
array('d', [2.1, 3.1])
array('d', [1.1, 2.1, 3.1])
All values
1.1
2.2
3.8
3.1
3.7
1.2
4.6
specific values
2.2
3.8
[20, 30, 40]
[1, 2, 3, 4]
[1 2 3 4]
3
[10, 25, 30]
[1, 2, 3, 4]
[1, 2, 3]
a
b
c
a
b
c
1
2
3
[80, 72, 90]
2
30
array('i', [10, 20, 35, 40, 50])
3
(138965466493120, 6)
0
[11 12 13 14 15]
[ 2  4  6  8 10]
[ 1  4  9 16 25]
15
3.0
1
5
1.4142135623730951
(2, 2)
[[1]
 [2]
 [3]
 [4]]
[1 2 3 4]
[[1 2]
 [3 4]]
[False False False  True  True]
[4 5]
[1 2 3 5]
[1 2 3]
array('d', [20.0, 35.0, 55.0, 65.0])
Element at 2nd index of array is:  55
This shows that element 55 is removed from the array. Updated Array is:  array('i', [20, 35, 65])
This shows that element which is at the last index of array removed. Updated Array is:  array('i', [20, 35, 55])


# **What is an Array in Python?**
An array is basically a data structure which can hold more than one value at a time. It is a collection or ordered series of elements of the same type.

Example:

a=arr.array('d',[1.2,1.3,2.3])
We can loop through the array items easily and fetch the required values by just specifying the index number. Arrays are mutable(changeable) as well, therefore, you can perform various manipulations as required.

In [4]:
import array as arr

myArr = arr.array('i', [20, 35, 55, 65])

indOfElement = 2

accessedElement = myArr[indOfElement]

print('Element at 2nd index of array is: ', accessedElement)

import array as arr

myArr = arr.array('i', [20, 35, 55, 65])

indexOfSearchedElement = myArr.index(35)

print('index of element 35 in array is: ', indexOfSearchedElement)


import array as arr

myArr = arr.array('i', [20, 35, 55, 65])

print('array before updating the value: ', myArr)

myArr[2] = 100

print('array after updating the 2nd index of the array: ',myArr)



import array as arr

myArr = arr.array('i', [20, 35, 55, 65])

print('array before reversing the array: ', myArr)

myArr.reverse()

print('array after reversing the array: ', myArr)


import array as arr

myMarks = arr.array('i', [70, 60, 50, 20, 100])

print('marks array before updating the marks: ', myMarks)

indOf20 = myMarks.index(20)

myMarks[indOf20] = 90

print('marks array after updating the marks: ', myMarks)

my_list = [1, 2, 3, 4, 5]
sliced_list = my_list[1:4]  # Extract elements from index 1 to 3 (exclusive)
print(sliced_list)


my_list = [1, 2, 3, 4, 5]
sliced_list = my_list[::2]  # Extract elements at even indices
print(sliced_list)


my_array = [1, 2, 3, 4, 5]
count = len(my_array)
print(count)


import numpy

my_array = numpy.array([0, 1, 2, 3, 4])
print(my_array)

# Expected output: [0 1 2 3 4]

import numpy

my_array = numpy.array([0, 1, 2, 3, 4])
print(type(my_array))

# Expected output: <class 'numpy.ndarray'>

import numpy as np

a_list = [1, 2, 3, 4]
print(a_list)

# Expected output: [1, 2, 3, 4]

import numpy as np

a_list = [1, 2, 3, 4]
an_array = np.array(a_list)
print(an_array)

# Expected output: [1 2 3 4]

import numpy as np

array_A = np.array([1, 2, 3])
array_B = np.array([4, 5, 6])

print(array_A + array_B)

# Expected output: [5 7 9]

import numpy as np

months_array = np.array(['Jan', 'Feb', 'March', 'Apr', 'May'])
print(months_array[3])

# Expected output: Apr

import numpy as np

months_array = np.array(['Jan', 'Feb', 'March', 'Apr', 'May'])
print(months_array[2:5])

# Expected output: ['March', 'Apr', 'May']

import numpy as np

# Lists
prices = [170.12, 93.29, 55.28, 145.30, 171.81, 59.50, 100.50]
earnings = [9.2, 5.31, 2.41, 5.91, 15.42, 2.51, 6.79]

# NumPy arrays
prices_array = np.array(prices)
earnings_array = np.array(earnings)

# Print the arrays
print(prices_array)
print(earnings_array)

# Expected output:
# [170.12  93.29  55.28 145.3  171.81  59.5  100.5 ]
# [ 9.2   5.31  2.41  5.91 15.42  2.51  6.79]

colors = ["red", "green", "blue"]
# Indexes:   0      1       2

print(colors[0])  # Output: red
print(colors[2])  # Output: blue

months = ["Jan", "Feb", "Apr", "May", "Jun"]
# Output the 3rd element (remember, indexing starts at 0)
print(months[2])

fruits = ["apple", "banana", "orange", "grape"]
fruits[1] = "kiwi"
print(fruits)  # Output: ["apple", "kiwi", "orange", "grape"]

months = ["Jan", "Feb", "Dec", "Apr", "May"]
# Update the 3rd month (index 2) to "Mar"
months[2] = "Mar"
print(months)



pets = ['cat', 'dog', 'mouse']
print(len(pets)) # Output: 3

fruits = ["apple", "banana", "cherry"]
fruits.append("orange")
print(fruits)  # Output: ["apple", "banana", "cherry", "orange"]

fruits.insert(1, "kiwi")
print(fruits)  # Output: ["apple", "kiwi", "banana", "cherry", "orange"]

fruits = ["apple", "banana", "cherry", "banana"]
fruits.remove("banana")
print(fruits)  # Output: ["apple", "cherry", "banana"]

removed_fruit = fruits.pop(1)
print(removed_fruit)  # Output: cherry
print(fruits)  # Output: ["apple", "banana"]


list1 = [1, 2, 3]
list2 = [4, 5, 6]
combined_list = list1 + list2
print(combined_list)  # Output: [1, 2, 3, 4, 5, 6]

list1 = ['Hero', 'Maybe Man', 'Run', 'Enemy']
list2 = ['Annihilate', 'Die for you', 'Am I dreaming', 'Burn the house down']
combined_list = list1 + list2
print(combined_list)



fruits = input().split()
print(fruits)

numbers = list(map(int, input().split()))
print(numbers)

Element at 2nd index of array is:  55
index of element 35 in array is:  1
array before updating the value:  array('i', [20, 35, 55, 65])
array after updating the 2nd index of the array:  array('i', [20, 35, 100, 65])
array before reversing the array:  array('i', [20, 35, 55, 65])
array after reversing the array:  array('i', [65, 55, 35, 20])
marks array before updating the marks:  array('i', [70, 60, 50, 20, 100])
marks array after updating the marks:  array('i', [70, 60, 50, 90, 100])
[2, 3, 4]
[1, 3, 5]
5
[0 1 2 3 4]
<class 'numpy.ndarray'>
[1, 2, 3, 4]
[1 2 3 4]
[5 7 9]
Apr
['March' 'Apr' 'May']
[170.12  93.29  55.28 145.3  171.81  59.5  100.5 ]
[ 9.2   5.31  2.41  5.91 15.42  2.51  6.79]
red
blue
Apr
['apple', 'kiwi', 'orange', 'grape']
['Jan', 'Feb', 'Mar', 'Apr', 'May']
3
['apple', 'banana', 'cherry', 'orange']
['apple', 'kiwi', 'banana', 'cherry', 'orange']
['apple', 'cherry', 'banana']
cherry
['apple', 'banana']
[1, 2, 3, 4, 5, 6]
['Hero', 'Maybe Man', 'Run', 'Enemy', 'Annihila

# **Removing/ Deleting elements of an array:**
Array elements can be removed using pop() or remove() method. The difference between these two functions is that the former returns the deleted value whereas the latter does not.

The pop() function takes either no parameter or the index value as its parameter. When no parameter is given, this function pops() the last element and returns it. When you explicitly supply the index value, the pop() function pops the required elements and returns it.

In [5]:
# creating a list containing elements
# belonging to different data types
sample_list = [1, "Yash", ['a', 'e']]
print(type(sample_list))
print(sample_list)

# importing "array" for array creations
import array as arr

# creating an array with integer type
a = arr.array('i', [1, 2, 3])
print(type(a))
for i in a:
    print(i, end=" ")

from array import *
array_num = array('i', [1, 3, 5, 7, 9])
print("Original array: "+str(array_num))
print("Append 11 at the end of the array:")
array_num.append(11)
print("New array: "+str(array_num))


from array import *
array_num = array('i', [1, 3, 5, 3, 7, 1, 9, 3])
print("Original array: "+str(array_num))
array_num.reverse()
print("Reverse the order of the items:")
print(str(array_num))


from array import *
array_num = array('i', [1, 3, 5, 7, 9])
print("Original array: "+str(array_num))
print("Length in bytes of one array item: "+str(array_num.itemsize))


from array import *
array_num = array('i', [1, 3, 5, 7, 9])
print("Original array: "+str(array_num))
print("Current memory address and the length in elements of the buffer: "+str(array_num.buffer_info()))
print("The size of the memory buffer in bytes: "+str(array_num.buffer_info()[1] * array_num.itemsize))


from array import *
array_num = array('i', [1, 3, 5, 7, 9])
print("Original array: "+str(array_num))
print("Current memory address and the length in elements of the buffer: "+str(array_num.buffer_info()))
print("The size of the memory buffer in bytes: "+str(array_num.buffer_info()[1] * array_num.itemsize))


from array import *
array_num = array('i', [1, 3, 5, 3, 7, 9, 3])
print("Original array: "+str(array_num))
print("Number of occurrences of the number 3 in the said array: "+str(array_num.count(3)))


from array import *
array_num = array('i', [1, 3, 5, 7, 9])
print("Original array: "+str(array_num))
array_num.extend(array_num)
print("Extended array: "+str(array_num))


from array import *
print("Bytes to String: ")
x = array('b', [119, 51, 114, 101,  115, 111, 117, 114, 99, 101])
s = x.tobytes()
print(s)


from array import *
num_list = [1, 2, 6, -8]
array_num = array('i', [])
print("Items in the list: " + str(num_list))
print("Append items from the list: ")
array_num.fromlist(num_list)
print("Items in the array: "+str(array_num))


from array import *
array_num = array('i', [1, 3, 5, 7, 9])
print("Original array: "+str(array_num))
print("Insert new value 4 before 3:")
array_num.insert(1, 4)
print("New array: "+str(array_num))


from array import *
array_num = array('i', [1,3,5,7,9])
for i in array_num:
    print(i)
print("Access first three items individually")
print(array_num[0])
print(array_num[1])
print(array_num[2])


from array import *

#an array of floating point values
numbers = array('d',[10.0,20.0,30.0])

print(numbers)

#output

#array('d', [10.0, 20.0, 30.0])

import array as arr

numbers = arr.array('i',[10,20,30])


print(len(numbers))

#output
# 3

import array as arr

numbers = arr.array('i',[10,20,30])

print(numbers[0]) # gets the 1st element
print(numbers[1]) # gets the 2nd element
print(numbers[2]) # gets the 3rd element

#output

#10
#20
#30

import array as arr

numbers = arr.array('i',[10,20,30])

print(numbers[-1]) #gets last item
print(numbers[-2]) #gets second to last item
print(numbers[-3]) #gets first item

#output

#30
#20
#10

import array as arr

numbers = arr.array('i',[10,20,30])

#search for the index of the value 10
print(numbers.index(10))

#output

#0

import array as arr


numbers = arr.array('i',[10,20,30,10,20,30])

#search for the index of the value 10
#will return the index number of the first instance of the value 10
print(numbers.index(10))

#output

#0

import array as arr

numbers = arr.array('i',[10,20,30])

print(numbers)

#output

#array('i', [10, 20, 30])

import array as arr

numbers = arr.array('i',[10,20,30])

for number in numbers:
    print(number)

#output
#10
#20
#30

import array as arr

values = arr.array('i',[10,20,30])

#prints each individual value in the array
for value in range(len(values)):
    print(values[value])

#output

#10
#20
#30



<class 'list'>
[1, 'Yash', ['a', 'e']]
<class 'array.array'>
1 2 3 Original array: array('i', [1, 3, 5, 7, 9])
Append 11 at the end of the array:
New array: array('i', [1, 3, 5, 7, 9, 11])
Original array: array('i', [1, 3, 5, 3, 7, 1, 9, 3])
Reverse the order of the items:
array('i', [3, 9, 1, 7, 3, 5, 3, 1])
Original array: array('i', [1, 3, 5, 7, 9])
Length in bytes of one array item: 4
Original array: array('i', [1, 3, 5, 7, 9])
Current memory address and the length in elements of the buffer: (138965466402224, 5)
The size of the memory buffer in bytes: 20
Original array: array('i', [1, 3, 5, 7, 9])
Current memory address and the length in elements of the buffer: (138965466403376, 5)
The size of the memory buffer in bytes: 20
Original array: array('i', [1, 3, 5, 3, 7, 9, 3])
Number of occurrences of the number 3 in the said array: 3
Original array: array('i', [1, 3, 5, 7, 9])
Extended array: array('i', [1, 3, 5, 7, 9, 1, 3, 5, 7, 9])
Bytes to String: 
b'w3resource'
Items in the list:

# **Adding/ Changing elements of an Array:**
We can add value to an array by using the append(), extend() and the insert (i,x) functions.

The append() function is used when we need to add a single element at the end of the array.