<a href="https://colab.research.google.com/github/digitechit07/Python-Tutorial-with-Excercise/blob/main/Python_Arrays_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **How to Slice an Array in Python**
To access a specific range of values inside the array, use the slicing operator, which is a colon :.

When using the slicing operator and you only include one value, the counting starts from 0 by default. It gets the first item, and goes up to but not including the index number you specify.

In [1]:
import array as arr

numbers = arr.array('i',[10,20,30])

print(numbers[0]) # gets the 1st element
print(numbers[1]) # gets the 2nd element
print(numbers[2]) # gets the 3rd element

#output

#10
#20
#30

import array as arr

numbers = arr.array('i',[10,20,30])

print(numbers[-1]) #gets last item
print(numbers[-2]) #gets second to last item
print(numbers[-3]) #gets first item

#output

#30
#20
#10

import array as arr

numbers = arr.array('i',[10,20,30])

#search for the index of the value 10
print(numbers.index(10))

#output

#0

import array as arr


numbers = arr.array('i',[10,20,30,10,20,30])

#search for the index of the value 10
#will return the index number of the first instance of the value 10
print(numbers.index(10))

#output

#0

import array as arr

numbers = arr.array('i',[10,20,30])

print(numbers)

#output

#array('i', [10, 20, 30])

import array as arr

numbers = arr.array('i',[10,20,30])

for number in numbers:
    print(number)

#output
#10
#20
#30

import array as arr

values = arr.array('i',[10,20,30])

#prints each individual value in the array
for value in range(len(values)):
    print(values[value])

#output

#10
#20
#30

import array as arr

#original array
numbers = arr.array('i',[10,20,30])

#get the values 10 and 20 only
print(numbers[:2])  #first to second position

#output

#array('i', [10, 20])

import array as arr

#original array
numbers = arr.array('i',[10,20,30])


#get the values 20 and 30 only
print(numbers[1:3]) #second to third position

#output

#array('i', [20, 30])

import array as arr

#original array
numbers = arr.array('i',[10,20,30])

#change the first element
#change it from having a value of 10 to having a value of 40
numbers[0] = 40

print(numbers)

#output

#array('i', [40, 20, 30])

import array as arr

#original array
numbers = arr.array('i',[10,20,30])

#add the integer 40 to the end of numbers
numbers.append(40)

print(numbers)

#output

#array('i', [10, 20, 30, 40])

import array as arr

#original array
numbers = arr.array('i',[10,20,30])

#add the integers 40,50,60 to the end of numbers
#The numbers need to be enclosed in square brackets

numbers.extend([40,50,60])

print(numbers)

#output

#array('i', [10, 20, 30, 40, 50, 60])

import array as arr

#original array
numbers = arr.array('i',[10,20,30])

#add the integer 40 in the first position
#remember indexing starts at 0

numbers.insert(0,40)

print(numbers)

#output

#array('i', [40, 10, 20, 30])

import array as arr

#original array
numbers = arr.array('i',[10,20,30])

numbers.remove(10)

print(numbers)

#output

#array('i', [20, 30])

import array as arr

#original array
numbers = arr.array('i',[10,20,30,10,20])

numbers.remove(10)

print(numbers)

#output

#array('i', [20, 30, 10, 20])

import array as arr

#original array
numbers = arr.array('i',[10,20,30,10,20])

#remove the first instance of 10
numbers.pop(0)

print(numbers)

#output

#array('i', [20, 30, 10, 20])



10
20
30
30
20
10
0
0
array('i', [10, 20, 30])
10
20
30
10
20
30
array('i', [10, 20])
array('i', [20, 30])
array('i', [40, 20, 30])
array('i', [10, 20, 30, 40])
array('i', [10, 20, 30, 40, 50, 60])
array('i', [40, 10, 20, 30])
array('i', [20, 30])
array('i', [20, 30, 10, 20])
array('i', [20, 30, 10, 20])


# **Methods For Performing Operations on Arrays in Python**
Arrays are mutable, which means they are changeable. You can change the value of the different items, add new ones, or remove any you don't want in your program anymore.

Let's see some of the most commonly used methods which are used for performing operations on arrays.

How to Change the Value of an Item in an Array
You can change the value of a specific element by speficying its position and assigning it a new value:


In [2]:
from array import *
array_num = array('i', [1, 3, 5, 7, 9])
print("Original array: "+str(array_num))
print("Remove the third item form the array:")
array_num.pop(2)
print("New array: "+str(array_num))


from array import *
array_num = array('i', [1, 3, 5, 3, 7, 1, 9, 3])
print("Original array: "+str(array_num))
print("Remove the first occurrence of 3 from the said array:")
array_num.remove(3)
print("New array: "+str(array_num))



from array import *
array_num = array('i', [1, 3, 5, 3, 7, 1, 9, 3])
print("Original array: "+str(array_num))
num_list = array_num.tolist()
print("Convert the said array to an ordinary list with the same items:")
print(num_list)


def test_duplicate(array_nums):
    nums_set = set(array_nums)
    return len(array_nums) != len(nums_set)
print(test_duplicate([1,2,3,4,5]))
print(test_duplicate([1,2,3,4, 4]))
print(test_duplicate([1,1,2,2,3,3,4,4,5]))


def find_first_duplicate(nums):
    num_set = set()
    no_duplicate = -1

    for i in range(len(nums)):

        if nums[i] in num_set:
            return nums[i]
        else:
            num_set.add(nums[i])

    return no_duplicate

print(find_first_duplicate([1, 2, 3, 4, 4, 5]))
print(find_first_duplicate([1, 2, 3, 4]))
print(find_first_duplicate([1, 1, 2, 3, 3, 2, 2]))


def is_samePatterns(colors, patterns):
    if len(colors) != len(patterns):
        return False
    sdict = {}
    pset = set()
    sset = set()
    for i in range(len(patterns)):
        pset.add(patterns[i])
        sset.add(colors[i])
        if patterns[i] not in sdict.keys():
            sdict[patterns[i]] = []

        keys = sdict[patterns[i]]
        keys.append(colors[i])
        sdict[patterns[i]] = keys

    if len(pset) != len(sset):
        return False

    for values in sdict.values():

        for i in range(len(values) - 1):
            if values[i] != values[i+1]:
                return False

    return True

print(is_samePatterns(["red",
 "green",
 "green"], ["a",
 "b",
 "b"]))

print(is_samePatterns(["red",
 "green",
 "greenn"], ["a",
 "b",
 "b"]))


def max_Product(arr):
    arr_len = len(arr)
    if (arr_len < 2):
        print("No pairs exists")
        return
    # Initialize max product pair
    x = arr[0]; y = arr[1]

    # Traverse through every possible pair
    for i in range(0, arr_len):

        for j in range(i + 1, arr_len):
            if (arr[i] * arr[j] > x * y):
                x = arr[i]; y = arr[j]

    return x,y

nums = [1, 2, 3, 4, 7, 0, 8, 4]
print("Original array:", nums)
print("Maximum product pair is:", max_Product(nums))

nums = [0, -1, -2, -4, 5, 0, -6]
print("\nOriginal array:", nums)
print("Maximum product pair is:", max_Product(nums))


from array import array
my_array = array('i', [10, 20, 30, 40, 50, 60])
for i in my_array:
    print(i)


from array import array
a = array("I", (12,25))
print("Array buffer start address in memory and number of elements.")
print(a.buffer_info())


from array import array
num_array = array('i', [10,20,30,40,50])
print("Length of the array is:")
print(len(num_array))


from array import array
a = array("I", (12,25))
print(a.itemsize)
a = array("f", (12.236,36.36))
print(a.itemsize)


from array import array
import binascii
array1 = array('i', [7, 8, 9, 10])
print('array1:', array1)
as_bytes = array1.tobytes()
print('Bytes:', binascii.hexlify(as_bytes))
array2 = array('i')
array2.frombytes(as_bytes)
print('array2:', array2)


import array as arr
def test(nums):
    return sorted(set(nums),key=nums.index)

array_num = arr.array('i', [1, 3, 5, 1, 3, 7, 9])
print("Original array:")
for i in range(len(array_num)):
    print(array_num[i], end=' ')
print("\nAfter removing duplicate elements from the said array:")
result = arr.array('i', test(array_num))
for i in range(len(result)):
    print(result[i], end=' ')
array_num = arr.array('i', [2, 4, 2, 6, 4, 8])
print("\nOriginal array:")
for i in range(len(array_num)):
    print(array_num[i], end=' ')
print("\nAfter removing duplicate elements from the said array:")
result = arr.array('i', test(array_num))
for i in range(len(result)):
    print(result[i], end=' ')


import array as arr
def test(nums):
    return sum(range(10, 21)) - sum(list(nums))

array_num = arr.array('i', [10, 11, 12, 13, 14, 16, 17, 18, 19, 20])
print("Original array:")
for i in range(len(array_num)):
    print(array_num[i], end=' ')
print("\nMissing number in the said array (10-20): ",test(array_num))

array_num = arr.array('i', [10, 11, 12, 13, 14, 15, 16, 17, 18, 19])
print("\nOriginal array:")
for i in range(len(array_num)):
    print(array_num[i], end=' ')
print("\nMissing number in the said array (10-20): ",test(array_num))

import array

# Declare an integer array
numbers = array.array('i', [1, 2, 3, 4, 5])
print(numbers)

# Declare a float array
decimals = array.array('f', [1.1, 2.2, 3.3])
print(decimals)

Original array: array('i', [1, 3, 5, 7, 9])
Remove the third item form the array:
New array: array('i', [1, 3, 7, 9])
Original array: array('i', [1, 3, 5, 3, 7, 1, 9, 3])
Remove the first occurrence of 3 from the said array:
New array: array('i', [1, 5, 3, 7, 1, 9, 3])
Original array: array('i', [1, 3, 5, 3, 7, 1, 9, 3])
Convert the said array to an ordinary list with the same items:
[1, 3, 5, 3, 7, 1, 9, 3]
False
True
True
4
-1
1
True
False
Original array: [1, 2, 3, 4, 7, 0, 8, 4]
Maximum product pair is: (7, 8)

Original array: [0, -1, -2, -4, 5, 0, -6]
Maximum product pair is: (-4, -6)
10
20
30
40
50
60
Array buffer start address in memory and number of elements.
(137552002471856, 2)
Length of the array is:
5
4
4
array1: array('i', [7, 8, 9, 10])
Bytes: b'0700000008000000090000000a000000'
array2: array('i', [7, 8, 9, 10])
Original array:
1 3 5 1 3 7 9 
After removing duplicate elements from the said array:
1 3 5 7 9 
Original array:
2 4 2 6 4 8 
After removing duplicate elements fro

# **Python array** is a fundamental data structure that stores multiple elements efficiently. Arrays organize data in contiguous memory locations for faster access and processing. Understanding what is array in Python helps developers write more efficient code.

Python offers several ways to work with arrays and data structures. You can use built-in lists, the array module, or NumPy arrays. Each method has unique advantages for different programming scenarios and applications.

Arrays are essential for data analysis, scientific computing, and machine learning projects. Learning how to declare array in Python improves your programming skills significantly. Modern developers often enhance their expertise through comprehensive online Software Engineering courses. These data structures form the backbone of efficient programming solutions. Arrays enable developers to handle large datasets with optimal performance.

In [4]:
# Create a list that acts like an array
my_array = [10, 20, 30, 40, 50]
print(my_array)

# Access elements by index
print(my_array[0])
print(my_array[2])

import array

# Create array with initial values
scores = array.array('i', [85, 92, 78, 96, 88])

# Create empty array and add elements
grades = array.array('f')
grades.append(3.5)
grades.append(3.8)
print(grades)

# Create array from range
range_array = array.array('i', range(1, 6))
print(range_array)

import numpy as np

# Create array from list
list_array = np.array([1, 2, 3, 4, 5])
print(list_array)

# Create array with zeros
zero_array = np.zeros(5)
print(zero_array)

# Create array with ones
ones_array = np.ones(3)
print(ones_array)

# Create array with range
range_array = np.arange(0, 10, 2)
print(range_array)

import numpy as np

# Create two arrays
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

# Mathematical operations
addition = arr1 + arr2
print(addition)

multiplication = arr1 * arr2
print(multiplication)

# Statistical operations
mean_value = np.mean(arr1)
print(mean_value)

sum_value = np.sum(arr2)
print(sum_value)

import numpy as np

# Create 2D array using nested lists
matrix_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix = np.array(matrix_list)
print(matrix)

# Create 2D array with zeros
zero_matrix = np.zeros((3, 4))
print(zero_matrix.shape)

# Create identity matrix
identity = np.eye(3)
print(identity)

import numpy as np

matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

# Access single element
element = matrix[1, 2] # Row 1, Column 2
print(element)

# Access entire row
row = matrix[0, :]
print(row)

# Access entire column
column = matrix[:, 1]
print(column)

# Access subarray
subarray = matrix[0:2, 1:3]
print(subarray)

import numpy as np

# Create sample array
arr = np.array([1, 2, 3, 4, 5])

# Basic operations
print("Original array:", arr)
print("Array length:", len(arr))
print("Array shape:", arr.shape)

# Modification operations
arr[0] = 10
print("Modified array:", arr)

# Mathematical operations
squared = arr ** 2
print("Squared values:", squared)

# Statistical operations
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Maximum:", np.max(arr))

import numpy as np

# Student grades data (rows: students, columns: subjects)
grades = np.array([
  [85, 92, 78, 90], # Student 1
  [78, 85, 82, 88], # Student 2
  [92, 88, 95, 93], # Student 3
  [76, 80, 75, 82], # Student 4
  [88, 91, 87, 89]  # Student 5
])

student_names = ["Alice", "Bob", "Charlie", "Diana", "Eve"]
subjects = ["Math", "Science", "English", "History"]

print("=== Student Grade Analysis ===")
print("Grades Matrix:")
print(grades)

# Calculate average grade for each student
student_averages = np.mean(grades, axis=1)
print("\nStudent Averages:")
for i, avg in enumerate(student_averages):
  print(f"{student_names[i]}: {avg:.2f}")

# Calculate average grade for each subject
subject_averages = np.mean(grades, axis=0)
print("\nSubject Averages:")
for i, avg in enumerate(subject_averages):
  print(f"{subjects[i]}: {avg:.2f}")

# Find top performer
top_student_index = np.argmax(student_averages)
print(f"\nTop Performer: {student_names[top_student_index]} ({student_averages[top_student_index]:.2f})")

# Find students below average
overall_average = np.mean(grades)
below_average = student_averages < overall_average
print(f"\nOverall Average: {overall_average:.2f}")
print("Students below average:")
for i, below in enumerate(below_average):
  if below:
    print(f"- {student_names[i]}: {student_averages[i]:.2f}")


import array

# Creating an array of integers
array_module = array.array('i', [20, 35, 55, 65])

# Printing the array
print(array_module)

import array as arr

# Creating a static array of 5 integers
numbers = arr.array('i', [1, 2, 3, 4, 5])
print(numbers)

# Creating a dynamic array using list
numbers = [10, 20, 30]

# Adding more elements
numbers.append(40)
numbers.extend([50, 60])
print(numbers)

import array as arr

# Creating an array of integers
numbers = arr.array('i', [10, 20, 30, 40, 50])
print("Integer Array:", numbers)

# Creating an array of floats
float_numbers = arr.array('f', [1.1, 2.2, 3.3, 4.4])
print("Float Array:", float_numbers)

import array as arr

# Creating an array of integers
numbers = arr.array('i', [5, 10, 15, 20, 25])

# Accessing elements using index
print(numbers[0])
print(numbers[2])

# Trying to access an index out of range will raise an error
print(numbers[1])  # IndexError: array index out of range



[10, 20, 30, 40, 50]
10
30
array('f', [3.5, 3.799999952316284])
array('i', [1, 2, 3, 4, 5])
[1 2 3 4 5]
[0. 0. 0. 0. 0.]
[1. 1. 1.]
[0 2 4 6 8]
[ 6  8 10 12]
[ 5 12 21 32]
2.5
26
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
60
[10 20 30]
[20 50 80]
[[20 30]
 [50 60]]
Original array: [1 2 3 4 5]
Array length: 5
Array shape: (5,)
Modified array: [10  2  3  4  5]
Squared values: [100   4   9  16  25]
Sum: 24
Mean: 4.8
Maximum: 10
=== Student Grade Analysis ===
Grades Matrix:
[[85 92 78 90]
 [78 85 82 88]
 [92 88 95 93]
 [76 80 75 82]
 [88 91 87 89]]

Student Averages:
Alice: 86.25
Bob: 83.25
Charlie: 92.00
Diana: 78.25
Eve: 88.75

Subject Averages:
Math: 83.80
Science: 87.20
English: 83.40
History: 88.40

Top Performer: Charlie (92.00)

Overall Average: 85.70
Students below average:
- Bob: 83.25
- Diana: 78.25
array('i', [20, 35, 55, 65])
array('i', [1, 2, 3, 4, 5])
[10, 20, 30, 40, 50, 60]
Integer Array: array('i', [10, 20, 30, 40, 50])
Float Array: array('f', 

# **How to Declare an Array in Python**
How to declare an array in Python depends on which implementation you choose. Python provides three main approaches for array declaration and creation.

Using the Array Module
The array module provides a space-efficient way to create arrays. You must import the module before using it in your code.