<a href="https://colab.research.google.com/github/digitechit07/Python-Tutorial-with-Excercise/blob/main/Python_Arrays_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Lists as a General-Purpose Array-like Structure:**
Python's built-in list type is a highly versatile, ordered, and mutable collection that can store elements of different data types. They are commonly used in situations where you might use an array in other languages.

In [1]:
# Creating and manipulating a list
my_list = [1, "hello", 3.14, True]
print(my_list[0])  # Accessing elements by index
my_list.append(5)  # Adding elements

import array

# Creating an array of signed integers ('i' type code)
my_array = array.array('i', [1, 2, 3, 4, 5])
print(my_array[2])

import numpy as np

# Creating a NumPy array
numpy_array = np.array([1, 2, 3, 4, 5])
print(numpy_array)

# Performing element-wise operations
new_array = numpy_array * 2
print(new_array)

import numpy as np
a = np.array([1, 2, 3, 4])

# Element-wise operations
print(a * 2)

# Multi-dimensional array
res = np.array([[1, 2], [3, 4]])
print(res * 2)

import array as arr
a = arr.array('i', [1, 2, 3])

# accessing First Araay
print(a[0])

# adding element to array
a.append(5)
print(a)

import array as arr
a = arr.array('i', [1, 2, 3])

for i in range(0, 3):
    print(a[i], end=" ")

import array as arr
a = arr.array('i', [1, 2, 3])
print(*a)

a.insert(1, 4)  # Insert 4 at index 1
print(*a)

import array as arr
a = arr.array('i', [1, 2, 3, 4, 5, 6])

print(a[0])
print(a[3])

b = arr.array('d', [2.5, 3.2, 3.3])
print(b[1])
print(b[2])

import array
a = array.array('i', [1, 2, 3, 1, 5])

# remove first occurance of 1
a.remove(1)
print(a)

# remove item at index 2
a.pop(2)
print(a)

import array as arr
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
b = arr.array('i', a)

res = a[3:8]
print(res)

res = a[5:]
print(res)

res = a[:]
print(res)

import array
a = array.array('i', [1, 2, 3, 1, 2, 5])

# index of 1st occurrence of 2
print(a.index(2))

# index of 1st occurrence of 1
print(a.index(1))

import array
a = array.array('i', [1, 2, 3, 1, 2, 5])

# update item at index 2
a[2] = 6
print(a)

# update item at index 4
a[4] = 8
print(a)

import array
a = array.array('i', [1, 2, 3, 4, 2, 5, 2])

count = a.count(2)
print(count)

import array
a = array.array('i', [1, 2, 3, 4, 5])

a.reverse()
print(*a)

import array as arr
a = arr.array('i', [1, 2, 3,4,5])

a.extend([6,7,8,9,10])
print(a)

import array

# Creating an array of integers

arr = array.array('i', [1, 2, 3, 4, 5])

print(arr)  # Output: array('i', [1, 2, 3, 4, 5])

import array

arr = array.array('i', [1, 2, 3, 4, 5])

# Accessing elements by index

print(arr[0])  # Output: 1

print(arr[2])  # Output: 3

import array

arr = array.array('i', [1, 2, 3, 4, 5])

# Getting the length of the array

length = len(arr)

print(length)  # Output: 5

import array

arr = array.array('i', [1, 2, 3, 4, 5])

# Looping through the array elements

for element in arr:

    print(element)

import array

arr = array.array('i', [1, 2, 3, 4, 5])

# Removing an element by value

arr.remove(3)

print(arr)  # Output: array('i', [1, 2, 4, 5])

import array

arr = array.array('i', [1, 2, 3, 4, 5])

# Slicing the array

slice_arr = arr[1:4]

print(slice_arr)  # Output: array('i', [2, 3, 4])

import array

arr = array.array('i', [1, 2, 3, 4, 5])

# Searching for an element

index = arr.index(3)

print(index)  # Output: 2

import array

arr = array.array('i', [1, 2, 3, 4, 5])

# Updating an element

arr[2] = 10

print(arr)  # Output: array('i', [1, 2, 10, 4, 5])

1
3
[1 2 3 4 5]
[ 2  4  6  8 10]
[2 4 6 8]
[[2 4]
 [6 8]]
1
array('i', [1, 2, 3, 5])
1 2 3 1 2 3
1 4 2 3
1
4
3.2
3.3
array('i', [2, 3, 1, 5])
array('i', [2, 3, 5])
[4, 5, 6, 7, 8]
[6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
1
0
array('i', [1, 2, 6, 1, 2, 5])
array('i', [1, 2, 6, 1, 8, 5])
3
5 4 3 2 1
array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
array('i', [1, 2, 3, 4, 5])
1
3
5
1
2
3
4
5
array('i', [1, 2, 4, 5])
array('i', [2, 3, 4])
2
array('i', [1, 2, 10, 4, 5])


# **Key Differences and Considerations:**
Homogeneity: Python lists can store elements of different data types, while array module arrays and NumPy arrays are designed for homogeneous data types.
Performance and Memory: array module arrays and NumPy arrays are generally more memory-efficient and offer better performance for numerical operations compared to Python lists, especially with large datasets.
Functionality: NumPy provides extensive functionality for mathematical and scientific computing, including linear algebra, Fourier transforms, and random number generation, which are not available in standard Python lists or the array module.

In [2]:
import array

# Creating an array of integers

arr = array.array('i', [1, 2, 3, 4, 5])

# Creating a list of integers

lst = [1, 2, 3, 4, 5]

# Demonstrating flexibility of lists

lst.append("six")

print(lst)  # Output: [1, 2, 3, 4, 5, 'six']

import sys

import array

arr = array.array('i', [1, 2, 3, 4, 5])

lst = [1, 2, 3, 4, 5]

print(sys.getsizeof(arr))  # Output: Size of array in bytes

print(sys.getsizeof(lst))  # Output: Size of list in bytes

import array

arr1 = array.array('i', [1, 2, 3])

arr2 = array.array('i', [4, 5, 6])

combined_arr = arr1 + arr2

print(combined_arr)  # Output: array('i', [1, 2, 3, 4, 5, 6])

import array

arr1 = array.array('i', [1, 2, 3])

arr2 = array.array('i', [1, 2, 3])

are_equal = arr1 == arr2

print(are_equal)  # Output: True

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

result = arr1 * arr2

print(result)  # Output: [ 4 10 18]

import array as arr

# creating an array with integer type
a = arr.array('i', [1, 2, 3])
print (type(a), a)

# creating an array with char type
a = arr.array('u', 'BAT')
print (type(a), a)

# creating an array with float type
a = arr.array('d', [1.1, 2.2, 3.3])
print (type(a), a)

from array import *
array1 = array('i', [10,20,30,40,50])
print (array1[0])
print (array1[2])

from array import *
array1 = array('i', [10,20,30,40,50])
array1.insert(1,60)
for x in array1:
 print(x)

from array import *
array1 = array('i', [10,20,30,40,50])
array1.remove(40)
for x in array1:
   print(x)

from array import *
array1 = array('i', [10,20,30,40,50])
print (array1.index(40))

from array import *
array1 = array('i', [10,20,30,40,50])
array1[2] = 80
for x in array1:
   print(x)


import array as arr

# creating array
numericArray = arr.array('i', [111, 211, 311, 411, 511])

#indexing
print (numericArray[0])
print (numericArray[1])
print (numericArray[2])


import array as arr

# creating array
numericArray = arr.array('i', [111, 211, 311, 411, 511])

# iteration through for loop
for item in numericArray:
   print(item)

import array as arr

# creating array
numericArray = arr.array('i', [111, 211, 311, 411, 511])

# use of enumerate() function
for loc, val in enumerate(numericArray):
    print(f"Index: {loc}, value: {val}")


import array as arr

# creating array
numericArray = arr.array('i', [111, 211, 311, 411, 511])

# slicing operation
print (numericArray[2:])
print (numericArray[0:3])


import array as arr
a = arr.array('i', [1, 2, 3])
a.append(10)
print (a)

import array as arr
a = arr.array('i', [1, 2, 3])
a.insert(1,20)
print (a)


import array as arr
a = arr.array('i', [1, 2, 3, 4, 5])
b = arr.array('i', [6,7,8,9,10])
a.extend(b)
print (a)


import array as arr

# creating array
numericArray = arr.array('i', [111, 211, 311, 411, 511])

# before removing array
print ("Before removing:", numericArray)
# removing array
numericArray.remove(311)
# after removing array
print ("After removing:", numericArray)

import array as arr

# creating array
numericArray = arr.array('i', [111, 211, 311, 411, 511])

# before removing array
print ("Before removing:", numericArray)
# removing array
numericArray.pop(3)
# after removing array
print ("After removing:", numericArray)

import array as arr
newArray = arr.array('i', [56, 42, 23, 85, 45])
for iterate in newArray:
   print (iterate)

import array as arr

# creating array
a = arr.array('i', [96, 26, 56, 76, 46])

# checking the length
l = len(a)

# loop variable
idx = 0

# while loop
while idx < l:
   print (a[idx])
   # incrementing the while loop
   idx+=1


[1, 2, 3, 4, 5, 'six']
100
104
array('i', [1, 2, 3, 4, 5, 6])
True
[ 4 10 18]
<class 'array.array'> array('i', [1, 2, 3])
<class 'array.array'> array('u', 'BAT')
<class 'array.array'> array('d', [1.1, 2.2, 3.3])
10
30
10
60
20
30
40
50
10
20
30
50
3
10
20
80
40
50
111
211
311
111
211
311
411
511
Index: 0, value: 111
Index: 1, value: 211
Index: 2, value: 311
Index: 3, value: 411
Index: 4, value: 511
array('i', [311, 411, 511])
array('i', [111, 211, 311])
array('i', [1, 2, 3, 10])
array('i', [1, 20, 2, 3])
array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
Before removing: array('i', [111, 211, 311, 411, 511])
After removing: array('i', [111, 211, 411, 511])
Before removing: array('i', [111, 211, 311, 411, 511])
After removing: array('i', [111, 211, 311, 511])
56
42
23
85
45
96
26
56
76
46


# **Python Arrays**

Lists in Python are the most flexible and commonly used data structure for sequential storage. They are similar to arrays in other languages but with several key differences:

Dynamic Typing: Python lists can hold elements of different types in the same list. We can have an integer, a string and even other lists all stored within a single list.
Dynamic Resizing: Lists are dynamically resized, meaning you can add or remove elements without declaring the size of the list upfront.
Built-in Methods: Python lists come with numerous built-in methods that allow for easy manipulation of the elements within them, including methods for appending, removing, sorting and reversing elements.

In [3]:
import array as arr
a = arr.array('d', [56, 42, 23, 85, 45])
l = len(a)
for x in range(l):
   print (a[x])


import array as arr
a = arr.array('i', [110, 220, 330, 440, 550])
b = a
print("Copied array:",b)
print (id(a), id(b))

import array as arr
import copy
a = arr.array('i', [110, 220, 330, 440, 550])
b = copy.deepcopy(a)
print("Copied array:",b)

import array as arr

# creating array
numericArray = arr.array('i', [88, 99, 77, 55, 66])

print("Original array:", numericArray)
revArray = numericArray[::-1]
print("Reversed array:",revArray)

import array as arr

# creating an array
numericArray = arr.array('i', [10,5,15,4,6,20,9])
print("Array before reversing:", numericArray)

# converting the array into list
newArray = numericArray.tolist()

# reversing the list
newArray.reverse()

# creating a new array from reversed list
revArray = arr.array('i', newArray)
print ("Array after reversing:",revArray)


import array as arr

# creating an array
numericArray = arr.array('i', [12, 10, 14, 16, 20, 18])
print("Array before reversing:", numericArray)

# reversing the array
newArray = list(reversed(numericArray))

# creating a new array from reversed list
revArray = arr.array('i', newArray)
print ("Array after reversing:",revArray)

import array as arr
a = arr.array('i', [10,5,15,4,6,20,9])
b = arr.array('i')
for i in range(len(a)-1, -1, -1):
   b.append(a[i])
print(a)
print(b)


import array as arr
a = arr.array('i', [10,5,15,4,6,20,9])
for i in range(0, len(a)):
   for j in range(i+1, len(a)):
      if(a[i] > a[j]):
         temp = a[i];
         a[i] = a[j];
         a[j] = temp;
print (a)

import array as arr

# creating array
orgnlArray = arr.array('i', [10,5,15,4,6,20,9])
print("Original array:", orgnlArray)
# converting to list
sortedList = orgnlArray.tolist()
# sorting the list
sortedList.sort()

# creating array from sorted list
sortedArray = arr.array('i', sortedList)
print("Array after sorting:",sortedArray)


import array as arr
a = arr.array('i', [4, 5, 6, 9, 10, 15, 20])
sorted(a)
print(a)

import array as arr

# creating two arrays
a = arr.array('i', [10,5,15,4,6,20,9])
b = arr.array('i', [2,7,8,11,3,10])

# merging both arrays
for i in range(len(b)):
   a.append(b[i])
print (a)


import array as arr
a = arr.array('i', [10,5,15,4,6,20,9])
b = arr.array('i', [2,7,8,11,3,10])
x = a.tolist()
y = b.tolist()
z = x+y
a = arr.array('i', z)
print (a)

import array as arr
a = arr.array('i', [88, 99, 77, 66, 44, 22])
b = arr.array('i', [12, 17, 18, 11, 13, 10])
a.extend(b)
print (a)

import array as arr
a = arr.array('d', [1.1, 3.5, 4.5])
print(a)

import array as arr
a = arr.array('i', [2, 4, 6, 8])

print("First element:", a[0])
print("Second element:", a[1])
print("Last element:", a[-1])

import array as arr

numbers_list = [2, 5, 62, 5, 42, 52, 48, 5]
numbers_array = arr.array('i', numbers_list)

print(numbers_array[2:5]) # 3rd to 5th
print(numbers_array[:-5]) # beginning to 4th
print(numbers_array[5:])  # 6th to end
print(numbers_array[:])   # beginning to end


import array as arr

numbers = arr.array('i', [1, 2, 3, 5, 7, 10])

# changing first element
numbers[0] = 0
print(numbers)     # Output: array('i', [0, 2, 3, 5, 7, 10])

# changing 3rd to 5th element
numbers[2:5] = arr.array('i', [4, 6, 8])
print(numbers)     # Output: array('i', [0, 2, 4, 6, 8, 10])


import array as arr

numbers = arr.array('i', [1, 2, 3])

numbers.append(4)
print(numbers)     # Output: array('i', [1, 2, 3, 4])

# extend() appends iterable to the end of the array
numbers.extend([5, 6, 7])
print(numbers)     # Output: array('i', [1, 2, 3, 4, 5, 6, 7])


import array as arr

odd = arr.array('i', [1, 3, 5])
even = arr.array('i', [2, 4, 6])

numbers = arr.array('i')   # creating empty array of integer
numbers = odd + even

print(numbers)

'''
import array as arr

number = arr.array('i', [1, 2, 3, 3, 4])

del number[2]  # removing third element
print(number)  # Output: array('i', [1, 2, 3, 4])

del number  # deleting entire array
print(number)  # Error: array is not defined
'''

import array as arr

numbers = arr.array('i', [10, 11, 12, 12, 13])

numbers.remove(12)
print(numbers)   # Output: array('i', [10, 11, 12, 13])

print(numbers.pop(2))   # Output: 12
print(numbers)   # Output: array('i', [10, 11, 13])




56.0
42.0
23.0
85.0
45.0
Copied array: array('i', [110, 220, 330, 440, 550])
138415627816048 138415627816048
Copied array: array('i', [110, 220, 330, 440, 550])
Original array: array('i', [88, 99, 77, 55, 66])
Reversed array: array('i', [66, 55, 77, 99, 88])
Array before reversing: array('i', [10, 5, 15, 4, 6, 20, 9])
Array after reversing: array('i', [9, 20, 6, 4, 15, 5, 10])
Array before reversing: array('i', [12, 10, 14, 16, 20, 18])
Array after reversing: array('i', [18, 20, 16, 14, 10, 12])
array('i', [10, 5, 15, 4, 6, 20, 9])
array('i', [9, 20, 6, 4, 15, 5, 10])
array('i', [4, 5, 6, 9, 10, 15, 20])
Original array: array('i', [10, 5, 15, 4, 6, 20, 9])
Array after sorting: array('i', [4, 5, 6, 9, 10, 15, 20])
array('i', [4, 5, 6, 9, 10, 15, 20])
array('i', [10, 5, 15, 4, 6, 20, 9, 2, 7, 8, 11, 3, 10])
array('i', [10, 5, 15, 4, 6, 20, 9, 2, 7, 8, 11, 3, 10])
array('i', [88, 99, 77, 66, 44, 22, 12, 17, 18, 11, 13, 10])
array('d', [1.1, 3.5, 4.5])
First element: 2
Second element: 4
La

# **NumPy Arrays**
NumPy arrays are a part of the NumPy library, which is a powerful tool for numerical computing in Python. These arrays are designed for high-performance operations on large volumes of data and support multi-dimensional arrays and matrices. This makes them ideal for complex mathematical computations and large-scale data processing.

Features:
Multi-dimensional support: NumPy arrays can handle more than one dimension, making them suitable for matrix operations and more complex mathematical constructs.
Broad broadcasting capabilities: They can perform operations between arrays of different sizes and shapes, a feature known as broadcasting.
Efficient storage and processing: NumPy arrays are stored more efficiently than Python lists and provide optimized performance for numerical operations.